name: GitHub Pages Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Fix Rollup native binary (Linux)
        working-directory: ./frontend
        run: |
          npm install @rollup/rollup-linux-x64-gnu --save-dev --force
          npm rebuild rollup --force

      - name: Build
        working-directory: ./frontend
        run: npm run build

      - name: Detect build folder
        id: detect-folder
        run: |
          if [ -d "frontend/dist" ]; then
            echo "build_dir=frontend/dist" >> $GITHUB_OUTPUT
          elif [ -d "frontend/build" ]; then
            echo "build_dir=frontend/build" >> $GITHUB_OUTPUT
          else
            echo "❌ No build folder found!"
            exit 1
          fi

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          branch: gh-pages
          folder: ${{ steps.detect-folder.outputs.build_dir }}
